### PR TITLE
Support parsing python pre-release versions

### PR DESCRIPTION
**Pull request by justinmchase**
## Proposed changes

Python pre-release versions aren't quite the same as standard semver. This change parses that case and transforms them into standard semver.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## Checklist

- [x] I have read the
      [CONTRIBUTING](https://github.com/Optum/oss-template/blob/main/CONTRIBUTING.md)
      doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by JoshuaTheMiller — DISMISSED** [review]
Gotta love regex 👍

Is there any documentation around python pre-release versions that would be handy to link in this repo and/or near these changes?

**Comment by justinmchase** [comment]
It looks like this is the python docs on versions:
https://peps.python.org/pep-0440/#public-version-identifiers

**Comment by justinmchase** [comment]
@JoshuaTheMiller You know what they say, if you have a problem that requires a regular expression to solve it, now you have two problems.

**Review by JoshuaTheMiller — APPROVED** [review]
Thank you for adding more docs to this PR 🙌

**Pull request merged**
